### PR TITLE
Auto-adding "Needs Review" to Bug Issues

### PR DESCRIPTION
**Pull request by weaverryan**
See #4 

* Add "Status: Needs Review" to issues only that are labeled as a "Bug"
* But don't update the "Status" if the issue already has a different status

### CODE REVIEW

**Comment by webmozart** [comment]
Awesome, thanks! See #12 for a PR to your PR :)

**Comment by weaverryan** [comment]
Sweet, let's do it! Carson just "grew up" a bit with your PR ;)

**Comment by weaverryan** [comment]
this is deployed, so, for example, the auto-labeling of bugs is working now on weaverryan/symfony#5

I have a message out to Mr Fab about getting this on symfony/symfony

**Comment by webmozart** [comment]
\o/

**Pull request merged**
